version: "3"

volumes:
  api:

services:
  microservice-2:
    container_name: pessoa
    build:
      context: .
    stop_signal: SIGINT
    ports:
      - "5002:5002"
    volumes:
      - api:/api
    restart: always
    networks:
      - mvp3
    command: ["python", "run.py"]

networks:
  mvp3:
    driver: bridge
